[package]
name = "dwo-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
cron.workspace = true
dwo-agent-service = { path = "../dwo-agent-service" }
dwo-channels = { path = "../dwo-channels" }
dwo-command = { path = "../dwo-command" }
dwo-context = { path = "../dwo-context" }
dwo-mcp = { path = "../dwo-mcp" }
dwo-protocol = { path = "../dwo-protocol" }
dwo-project = { path = "../dwo-project" }
dwo-tools = { path = "../dwo-tools" }
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
