[package]
name = "dwo-agent-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dwo-agent-core = { path = "../dwo-agent-core" }
dwo-agent-supervisor = { path = "../dwo-agent-supervisor" }
serde_yaml.workspace = true
