[package]
name = "dwo-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "dwo"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
dwo-cli = { path = "../dwo-cli" }
dwo-host = { path = "../dwo-host" }
dwo-ipc = { path = "../dwo-ipc" }
dwo-websocket = { path = "../dwo-websocket" }
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
